name: Update Readwise Articles

on:
  schedule:
    - cron: '0 0 * * *'  # 运行在每天 UTC 0:00
  workflow_dispatch:  # 允许手动触发

jobs:
  update-articles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      env:
       GITHUB_TOKEN: ${{ secrets.READWISE }}
      run: python readwise.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update articles $(date +'%Y-%m-%d')" && git push)
